### Building a Training Pipeline Manually without PyTorch

Here I am trying to build a pipeline which would be similar to general flow of training.

In [1]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [46]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [47]:
df.shape

(569, 33)

In [48]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True) # These 2 columns are not required

In [49]:
X = df.iloc[:, 1:]
X.head(5)

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [50]:
y = df.iloc[:, 0]
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [51]:
# Train test Splits

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2)

In [52]:
# we can see that the different features are of different scalles, the model might not perform well. Hence we need to Scale this

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [53]:
X_train

array([[-1.22020032, -0.86983717, -1.19901392, ..., -0.75624141,
        -0.65531528,  0.41604167],
       [-0.83570844,  0.09204067, -0.83548192, ..., -1.43533093,
         0.59373331, -1.04033349],
       [ 0.41886082,  0.19559211,  0.35433311, ...,  0.58234563,
         0.82298906,  0.10276112],
       ...,
       [-0.28963477, -0.18409651, -0.26456589, ...,  1.40671751,
         1.5550264 ,  1.814964  ],
       [ 0.55047858, -0.78009258,  0.56171713, ...,  0.14529289,
         0.373964  ,  0.28108171],
       [-0.53326764, -0.10125536, -0.59394053, ..., -1.13979286,
        -0.57309942, -0.6690581 ]])

In [54]:
#we have seen that y target is binary hence we need to convert it to 0 and 1

# We will perform Label Encoding

enc = LabelEncoder()
y_train = enc.fit_transform(y_train)
y_test = enc.transform(y_test)



In [55]:
y_train[:10]

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0])


## Converting Numpy Array to PyTorch Tensors

In [56]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [57]:
print(X_train_tensor.shape, X_test_tensor.shape )
print(y_train_tensor.shape, y_test_tensor.shape)

torch.Size([455, 30]) torch.Size([114, 30])
torch.Size([455]) torch.Size([114])


In [58]:
X_train_tensor.dtype

torch.float64

In [59]:
y_train_tensor

tensor([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,

In [60]:
torch.zeros(1, dtype=torch.float64)

tensor([0.], dtype=torch.float64)

# **Defining Model**

Here we are trying to have a simple forward pass with binary output and binary loss function.

In [65]:
class SimpleNN():

  def __init__(self, X): # This is constructor
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True) # as we have 30 independent features i.e. x1, x2, x3 .... x30. Hence we need to have same dim for weight parameter i.e. w1, w2, w3, ... w30. because here fuction would be y = w1*x1 + w2*x2 + .... w30*x30 + b
    # Here we have to match data type with the datatype of input hence float64. Also these are the parameters that need to get updated through backpropagation. Hence required_grad = True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True) # because we would be adding just 1 bias term to our function

  # lets define forward pass function
  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  # Lets also define the loss function
  def loss_function(self, y_pred, y_target):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





Important Parameters

In [84]:
learning_rate = 0.1
epochs = 200

In [85]:
# define Model
model = SimpleNN(X_train_tensor) # we need to pass X_train_tensor because we have defined input parameter in its constructor

## **Training Loop**

In [86]:
for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor) # this will output us the sigmoid outputs which are the logit values i.e. probabilities

  # Calculate the Loss
  loss = model.loss_function(y_pred, y_train_tensor)

  # Backward Pass
  loss.backward()

  # Update Gradients
  with torch.no_grad(): # Here we need to update our parameters and as this 2 parameters have require grad on, we don't want gradient tracking while updating the value
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Now Zero Gradients - This is done to remove all grad for next epoch, that is been accumulated in current epoch
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  if epoch % 10 == 0:
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.7269775059103867
Epoch: 11, Loss: 2.2241769073807567
Epoch: 21, Loss: 0.9744898348824939
Epoch: 31, Loss: 0.7772033202968609
Epoch: 41, Loss: 0.729091321160036
Epoch: 51, Loss: 0.7077060084144943
Epoch: 61, Loss: 0.6975860093728175
Epoch: 71, Loss: 0.6921564460422728
Epoch: 81, Loss: 0.6887971928765066
Epoch: 91, Loss: 0.6864538911831408
Epoch: 101, Loss: 0.6846733740038939
Epoch: 111, Loss: 0.6832418774659843
Epoch: 121, Loss: 0.6820478444388977
Epoch: 131, Loss: 0.6810271997025517
Epoch: 141, Loss: 0.6801399214266096
Epoch: 151, Loss: 0.6793591917488566
Epoch: 161, Loss: 0.6786659722111213
Epoch: 171, Loss: 0.6780460981789317
Epoch: 181, Loss: 0.6774886273482016
Epoch: 191, Loss: 0.6769848518208648


In [89]:
len(model.weights) , model.weights

(30,
 tensor([[ 0.2149],
         [ 0.1926],
         [ 0.2832],
         [-0.1552],
         [-0.1835],
         [-0.1843],
         [ 0.0352],
         [-0.4315],
         [ 0.0501],
         [ 0.3577],
         [-0.0297],
         [ 0.0879],
         [ 0.3169],
         [-0.3818],
         [-0.0964],
         [-0.2227],
         [ 0.1920],
         [-0.1855],
         [ 0.1660],
         [ 0.0499],
         [ 0.3603],
         [-0.2662],
         [-0.1268],
         [-0.0581],
         [ 0.2556],
         [-0.1027],
         [ 0.0357],
         [ 0.3597],
         [-0.1656],
         [-0.0527]], dtype=torch.float64, requires_grad=True))

In [90]:
model.bias

tensor([-0.4556], dtype=torch.float64, requires_grad=True)

## **Evaluation**

In [91]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6929824352264404


In [ ]:
# THe model is definitely performing very poor, but we get the context how the flow works. This becomes very easy when we use Torch library and its different modules like nn, optime and many more.