In [1]:
import numpy as np
import time

In [2]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr1 = np.arange(1,10,2)
arr1


array([1, 3, 5, 7, 9])

In [5]:
arr1[2]

5

In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr3 =  np.zeros((2,3))

In [16]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr3 = np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
arr4 = np.identity(4)
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
arr5 = np.ones((2,3,3))
arr5

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
arr6 = np.linspace(0,10,5)
arr6

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
arr8 = arr1.copy()
arr8

array([1, 3, 5, 7, 9])

In [26]:
arr1

array([1, 3, 5, 7, 9])

In [28]:
arr8[3] = 88
arr8

array([ 1,  3,  5, 88,  9])

In [29]:
arr1

array([1, 3, 5, 7, 9])

In [37]:
arr5.shape

(2, 3, 2)

In [41]:
arr5.ndim

3

In [30]:
arr9 = np.ones((2,3,4,2))
arr9

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [45]:
arr9.ndim

4

In [47]:
arr5

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
arr5.size

18

## Numpy vs List

In [9]:
# list

x = list(range(10000000))
y = list(range(10000000,20000000))

start_time = time.time()

res = [x+y for x,y in zip(x,y)]

print(time.time()-start_time)

1.0748894214630127


In [10]:
res

[10000000,
 10000002,
 10000004,
 10000006,
 10000008,
 10000010,
 10000012,
 10000014,
 10000016,
 10000018,
 10000020,
 10000022,
 10000024,
 10000026,
 10000028,
 10000030,
 10000032,
 10000034,
 10000036,
 10000038,
 10000040,
 10000042,
 10000044,
 10000046,
 10000048,
 10000050,
 10000052,
 10000054,
 10000056,
 10000058,
 10000060,
 10000062,
 10000064,
 10000066,
 10000068,
 10000070,
 10000072,
 10000074,
 10000076,
 10000078,
 10000080,
 10000082,
 10000084,
 10000086,
 10000088,
 10000090,
 10000092,
 10000094,
 10000096,
 10000098,
 10000100,
 10000102,
 10000104,
 10000106,
 10000108,
 10000110,
 10000112,
 10000114,
 10000116,
 10000118,
 10000120,
 10000122,
 10000124,
 10000126,
 10000128,
 10000130,
 10000132,
 10000134,
 10000136,
 10000138,
 10000140,
 10000142,
 10000144,
 10000146,
 10000148,
 10000150,
 10000152,
 10000154,
 10000156,
 10000158,
 10000160,
 10000162,
 10000164,
 10000166,
 10000168,
 10000170,
 10000172,
 10000174,
 10000176,
 10000178,
 10000180,

In [11]:
x = np.arange(1000000)
y = np.arange(1000000,2000000)

start_time = time.time()

res1 = np.add(x,y)

print(time.time()-start_time)

0.015705585479736328


In [12]:
res1

array([1000000, 1000002, 1000004, ..., 2999994, 2999996, 2999998])

## Reshape

In [13]:
arr11 = np.arange(24).reshape(2,3,4) # reshape can only happen if no of given array elements is equal to the output of multiplication of reshape size
#i.e. here total ele is 24 and 2*3*4 = 24 . hen
arr11

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
arr11 =  np.arange(24).reshape(3,3,4) #the product of 3*3*4 does not match element nos.

ValueError: cannot reshape array of size 24 into shape (3,3,4)

In [18]:
arr11 = np.arange(24).reshape(6,4)
arr11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
arr11[:,2:3]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [23]:
arr11[4:,1:3]

array([[17, 18],
       [21, 22]])

In [24]:
for i in arr11:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [25]:
# if you want to get each element than use nditer
for i in np.nditer(arr11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [32]:
print(arr9.shape)
for i in np.nditer(arr9):
    print(i)

(2, 3, 4, 2)
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [36]:
arr11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
arr11.min()

0

In [37]:
arr11.min(axis=0)   # wiill give min from each column

array([0, 1, 2, 3])

In [38]:
arr11.min(axis=1) # wiill give min from each row

array([ 0,  4,  8, 12, 16, 20])

## Ravel

In [39]:
# ravel brings n dimension array to 1d array
print(arr9.ndim)
arr9_rav = arr9.ravel()
print(arr9_rav.ndim)

4
1


In [40]:
arr9_rav

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Transpose

In [43]:
arr11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
arr11.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

## Stacking

In [50]:
arr12 = np.arange(30).reshape(6,5)
arr12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
# for h stacking 2 arrays, there rows must be same

In [51]:
np.hstack((arr12, arr11))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3],
       [ 5,  6,  7,  8,  9,  4,  5,  6,  7],
       [10, 11, 12, 13, 14,  8,  9, 10, 11],
       [15, 16, 17, 18, 19, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 16, 17, 18, 19],
       [25, 26, 27, 28, 29, 20, 21, 22, 23]])

In [52]:
# for v stacking 2 arrays, there column must be same

In [55]:
arr13 = np.arange(35).reshape(7,5)
arr13

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [56]:
np.vstack((arr12, arr13))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])